#############################################################################
# Makefile for building: VLN1-hopur2.app/Contents/MacOS/VLN1-hopur2
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  VLN1-hopur2.pro
# Template: app
# Command: /Users/sindrirafn/Qt/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile VLN1-hopur2.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../Qt/5.5/clang_64/lib/QtSql.framework/Headers -I../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/sindrirafn/Qt/5.5/clang_64/lib
QMAKE         = /Users/sindrirafn/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = VLN1-hopur21.0.0
DISTDIR = /Users/sindrirafn/VLN1-hopur2/.tmp/VLN1-hopur21.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 -Wl,-rpath,/Users/sindrirafn/Qt/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/sindrirafn/Qt/5.5/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		computer.cpp \
		scientist.cpp \
		service.cpp \
		database.cpp \
		sciwindow.cpp \
		addsci.cpp \
		compwindow.cpp \
		linkwindow.cpp \
		addcomp.cpp moc_mainwindow.cpp \
		moc_sciwindow.cpp \
		moc_addsci.cpp \
		moc_compwindow.cpp \
		moc_linkwindow.cpp \
		moc_addcomp.cpp
OBJECTS       = main.o \
		mainwindow.o \
		computer.o \
		scientist.o \
		service.o \
		database.o \
		sciwindow.o \
		addsci.o \
		compwindow.o \
		linkwindow.o \
		addcomp.o \
		moc_mainwindow.o \
		moc_sciwindow.o \
		moc_addsci.o \
		moc_compwindow.o \
		moc_linkwindow.o \
		moc_addcomp.o
DIST          = ../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		VLN1-hopur2.pro mainwindow.h \
		computer.h \
		scientist.h \
		service.h \
		database.h \
		sciwindow.h \
		addsci.h \
		compwindow.h \
		linkwindow.h \
		addcomp.h main.cpp \
		mainwindow.cpp \
		computer.cpp \
		scientist.cpp \
		service.cpp \
		database.cpp \
		sciwindow.cpp \
		addsci.cpp \
		compwindow.cpp \
		linkwindow.cpp \
		addcomp.cpp
QMAKE_TARGET  = VLN1-hopur2
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = VLN1-hopur2.app/Contents/MacOS/VLN1-hopur2

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-mmacosx-version-min=10.9 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_sciwindow.h ui_addsci.h ui_compwindow.h ui_linkwindow.h ui_addcomp.h $(OBJECTS)  
	@test -d VLN1-hopur2.app/Contents/MacOS/ || mkdir -p VLN1-hopur2.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VLN1-hopur2.pro ../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		VLN1-hopur2.pro \
		/Users/sindrirafn/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/sindrirafn/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/sindrirafn/Qt/5.5/clang_64/lib/QtSql.framework/QtSql.prl \
		/Users/sindrirafn/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile VLN1-hopur2.pro
../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../Qt/5.5/clang_64/mkspecs/features/uic.prf:
../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../Qt/5.5/clang_64/mkspecs/features/lex.prf:
VLN1-hopur2.pro:
/Users/sindrirafn/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/sindrirafn/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/sindrirafn/Qt/5.5/clang_64/lib/QtSql.framework/QtSql.prl:
/Users/sindrirafn/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile VLN1-hopur2.pro

qmake_all: FORCE

VLN1-hopur2.app/Contents/PkgInfo: 
	@test -d VLN1-hopur2.app/Contents || mkdir -p VLN1-hopur2.app/Contents
	@$(DEL_FILE) VLN1-hopur2.app/Contents/PkgInfo
	@echo "APPL????" > VLN1-hopur2.app/Contents/PkgInfo
VLN1-hopur2.app/Contents/Resources/empty.lproj: 
	@test -d VLN1-hopur2.app/Contents/Resources || mkdir -p VLN1-hopur2.app/Contents/Resources
	@touch VLN1-hopur2.app/Contents/Resources/empty.lproj
	
VLN1-hopur2.app/Contents/Info.plist: 
	@test -d VLN1-hopur2.app/Contents || mkdir -p VLN1-hopur2.app/Contents
	@$(DEL_FILE) VLN1-hopur2.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.VLN1-hopur2,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,VLN1-hopur2,g" -e "s,@TYPEINFO@,????,g" ../Qt/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >VLN1-hopur2.app/Contents/Info.plist

all: Makefile \
		VLN1-hopur2.app/Contents/PkgInfo \
		VLN1-hopur2.app/Contents/Resources/empty.lproj \
		VLN1-hopur2.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h computer.h scientist.h service.h database.h sciwindow.h addsci.h compwindow.h linkwindow.h addcomp.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp computer.cpp scientist.cpp service.cpp database.cpp sciwindow.cpp addsci.cpp compwindow.cpp linkwindow.cpp addcomp.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui sciwindow.ui addsci.ui compwindow.ui linkwindow.ui addcomp.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r VLN1-hopur2.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_sciwindow.cpp moc_addsci.cpp moc_compwindow.cpp moc_linkwindow.cpp moc_addcomp.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_sciwindow.cpp moc_addsci.cpp moc_compwindow.cpp moc_linkwindow.cpp moc_addcomp.cpp
moc_mainwindow.cpp: ../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		sciwindow.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		addsci.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h \
		compwindow.h \
		linkwindow.h \
		mainwindow.h
	/Users/sindrirafn/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/sindrirafn/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/sindrirafn/VLN1-hopur2 -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtSql.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/sindrirafn/Qt/5.5/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_sciwindow.cpp: ../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		addsci.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h \
		sciwindow.h
	/Users/sindrirafn/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/sindrirafn/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/sindrirafn/VLN1-hopur2 -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtSql.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/sindrirafn/Qt/5.5/clang_64/lib sciwindow.h -o moc_sciwindow.cpp

moc_addsci.cpp: ../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h \
		addsci.h
	/Users/sindrirafn/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/sindrirafn/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/sindrirafn/VLN1-hopur2 -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtSql.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/sindrirafn/Qt/5.5/clang_64/lib addsci.h -o moc_addsci.cpp

moc_compwindow.cpp: ../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		computer.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		compwindow.h
	/Users/sindrirafn/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/sindrirafn/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/sindrirafn/VLN1-hopur2 -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtSql.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/sindrirafn/Qt/5.5/clang_64/lib compwindow.h -o moc_compwindow.cpp

moc_linkwindow.cpp: ../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		linkwindow.h
	/Users/sindrirafn/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/sindrirafn/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/sindrirafn/VLN1-hopur2 -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtSql.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/sindrirafn/Qt/5.5/clang_64/lib linkwindow.h -o moc_linkwindow.cpp

moc_addcomp.cpp: ../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h \
		compwindow.h \
		addcomp.h
	/Users/sindrirafn/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/sindrirafn/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/sindrirafn/VLN1-hopur2 -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtSql.framework/Headers -I/Users/sindrirafn/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/sindrirafn/Qt/5.5/clang_64/lib addcomp.h -o moc_addcomp.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_sciwindow.h ui_addsci.h ui_compwindow.h ui_linkwindow.h ui_addcomp.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_sciwindow.h ui_addsci.h ui_compwindow.h ui_linkwindow.h ui_addcomp.h
ui_mainwindow.h: mainwindow.ui
	/Users/sindrirafn/Qt/5.5/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_sciwindow.h: sciwindow.ui
	/Users/sindrirafn/Qt/5.5/clang_64/bin/uic sciwindow.ui -o ui_sciwindow.h

ui_addsci.h: addsci.ui
	/Users/sindrirafn/Qt/5.5/clang_64/bin/uic addsci.ui -o ui_addsci.h

ui_compwindow.h: compwindow.ui
	/Users/sindrirafn/Qt/5.5/clang_64/bin/uic compwindow.ui -o ui_compwindow.h

ui_linkwindow.h: linkwindow.ui
	/Users/sindrirafn/Qt/5.5/clang_64/bin/uic linkwindow.ui -o ui_linkwindow.h

ui_addcomp.h: addcomp.ui
	/Users/sindrirafn/Qt/5.5/clang_64/bin/uic addcomp.ui -o ui_addcomp.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		sciwindow.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		addsci.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h \
		compwindow.h \
		linkwindow.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		sciwindow.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		addsci.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h \
		compwindow.h \
		linkwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

computer.o: computer.cpp computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o computer.o computer.cpp

scientist.o: scientist.cpp Scientist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scientist.o scientist.cpp

service.o: service.cpp service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o service.o service.cpp

database.o: database.cpp database.h \
		scientist.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

sciwindow.o: sciwindow.cpp sciwindow.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		addsci.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h \
		ui_sciwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sciwindow.o sciwindow.cpp

addsci.o: addsci.cpp addsci.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h \
		ui_addsci.h \
		sciwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addsci.o addsci.cpp

compwindow.o: compwindow.cpp compwindow.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		computer.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		ui_compwindow.h \
		addcomp.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QStatusBar \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compwindow.o compwindow.cpp

linkwindow.o: linkwindow.cpp linkwindow.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_linkwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linkwindow.o linkwindow.cpp

addcomp.o: addcomp.cpp addcomp.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		service.h \
		scientist.h \
		database.h \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/QtSql \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../Qt/5.5/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		computer.h \
		compwindow.h \
		ui_addcomp.h \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addcomp.o addcomp.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_sciwindow.o: moc_sciwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sciwindow.o moc_sciwindow.cpp

moc_addsci.o: moc_addsci.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addsci.o moc_addsci.cpp

moc_compwindow.o: moc_compwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_compwindow.o moc_compwindow.cpp

moc_linkwindow.o: moc_linkwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_linkwindow.o moc_linkwindow.cpp

moc_addcomp.o: moc_addcomp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addcomp.o moc_addcomp.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

